# Generated by Django 3.2.7 on 2021-10-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211025_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
