# Generated by Django 3.2.7 on 2021-10-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211026_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='Русский', max_length=255, verbose_name='Язык'),
        ),
    ]
