# Generated by Django 3.2.7 on 2021-10-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211026_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='media/books/', verbose_name='Изображение'),
        ),
    ]
