# Generated by Django 3.2.7 on 2021-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='SLUG'),
        ),
    ]
