# Generated by Django 3.2.7 on 2021-11-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20211101_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotAuthUsersMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Сообщение незарегестрированного пользователя',
                'verbose_name_plural': 'Сообщения незарегестрированных пользователей',
            },
        ),
    ]
