# Generated by Django 3.2.7 on 2021-11-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_notauthusersmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notauthusersmessage',
            old_name='user',
            new_name='email',
        ),
    ]
